#pragma once

// ゲームの状態を表す列挙型
enum SCENE {
	SCENE_TITLE,
	SCENE_MENU,
	SCENE_GAME,
	SCENE_GAME_OVER,
	SCENE_GAME_CLEAR
};

// メニュー
enum MENU
{
	MENU_GAME_START,
	MENU_RETURN,
	MENU_TUTORIAL,
};

// 向ている方向
enum DIRECTION
{
	DIRECTION_LEFT,
	DIRECTION_RIGHT
};

// 弾の種類
enum BULLET_TYPE
{
	BULLET_TYPE_EXPLOSION,
	BULLET_TYPE_VIBRATION_LEFT,
	BULLET_TYPE_VIBRATION_RIGHT,
	BULLET_TYPE_RUBBLE,
};

// 敵の種類
enum ENEMY_TYPE
{
	ENEMY_TYPE_GROUND,
	ENEMY_TYPE_FLYING
};

// ボスの種類
enum BOSS_TYPE
{
	BOSS_TYPE_STAGE_1,
};

// パーティクルの種類
enum PARTICLE_TYPE
{
	PARTICLE_TYPE_COLLISION,
	PARTICLE_TYPE_AURA,
	PARTICLE_TYPE_CLOUD,
	PARTICLE_TYPE_BOMB,
	PARTICLE_TYPE_FIRE,
	PARTICLE_TYPE_SMOKE_BLACK,
	PARTICLE_TYPE_RUBBLE_GRAVITY,
	PARTICLE_TYPE_SPARK_LEFT,
	PARTICLE_TYPE_SPARK_RIGHT,
	PARTICLE_TYPE_SPARK,
	PARTICLE_TYPE_SUMMON,
	PARTICLE_TYPE_WALK,
	PARTICLE_TYPE_GRAVITY,
	PARTICLE_TYPE_GRAVITY_INVERT,
	PARTICLE_TYPE_RUBBLE_COLLISION,
	PARTICLE_TYPE_RUSH,
	PARTICLE_TYPE_BIG_BOMB,
	PARTICLE_TYPE_BIG_FIRE,
	PARTICLE_TYPE_BIG_SMOKE_BLACK,
};

// アイテムの種類
enum ITEM_TYPE
{
	ITEM_TYPE_BOM,
	ITEM_TYPE_TITLE,
};